Lviv9 Talks
lvivpy/lvivpy.github.io pull request #5
Opened 2020-03-10 21:05 UTC by srusskih

2020-03-10 22:23 UTC, playpauseandstop requested changes

2020-03-10 22:23 UTC, playpauseandstop commented on src/content/lvivpy9-talks.rst
> +:description: Пурші спікери та доповіді які нас очікують 18-го берегня
**Перші** і **березня**

2020-03-10 22:23 UTC, playpauseandstop commented on src/content/lvivpy9-talks.rst
> +
@srusskih 

Can you add my talk as well?

```rst
| **GitHub Actions for Python projects & applications**
| `Igor Davydenko <https://igordavydenko.com>`_, *Python developer*

* Розраховано для: Beginner, Middle
* Час: 20хв

"Раніше користуючись GitHub ти завжди замислювався яким чином перевіряти Python проєкти і апплікації: Jenkins, Travis CI, Circle CI, drone.io, чи може таки взяти і переїхати на Gitlab? Але зараз все змінилося. Я розповім, як об’єднати GitHub Actions з Python проєктом, або Python апплікацією, які труднощі при цьому виникають і як їх вирішити."
```

2020-03-11 06:45 UTC, srusskih commented on src/content/lvivpy9-talks.rst
> +
@playpauseandstop done

2020-03-11 08:49 UTC, playpauseandstop approved these changes

2020-03-11 10:44 UTC, merged